# Generated by Django 4.0.2 on 2022-04-11 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_category_importbill_importbillbook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbillbook',
            name='book',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.book'),
        ),
        migrations.AddField(
            model_name='importbillbook',
            name='importBill',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.importbill'),
        ),
        migrations.AddField(
            model_name='importbillbook',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
